name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: SoundTracks/

      - name: Set execute permissions for node_modules/.bin
        run: chmod -R 755 node_modules/.bin
        working-directory: SoundTracks/

      - name: Build the app
        run: npm run build --if-present
        working-directory: SoundTracks/

      - name: Run tests
        run: npm test
        working-directory: SoundTracks/
